//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchoolsDBEntities : DbContext
    {
        public SchoolsDBEntities()
            : base("name=SchoolsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int AddAssignmentToCourse(string coursetitle, string assignmenttitle)
        {
            var coursetitleParameter = coursetitle != null ?
                new ObjectParameter("coursetitle", coursetitle) :
                new ObjectParameter("coursetitle", typeof(string));
    
            var assignmenttitleParameter = assignmenttitle != null ?
                new ObjectParameter("assignmenttitle", assignmenttitle) :
                new ObjectParameter("assignmenttitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddAssignmentToCourse", coursetitleParameter, assignmenttitleParameter);
        }
    
        public virtual int AddStudentToAssignment(string assignment, string studentemail)
        {
            var assignmentParameter = assignment != null ?
                new ObjectParameter("assignment", assignment) :
                new ObjectParameter("assignment", typeof(string));
    
            var studentemailParameter = studentemail != null ?
                new ObjectParameter("studentemail", studentemail) :
                new ObjectParameter("studentemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddStudentToAssignment", assignmentParameter, studentemailParameter);
        }
    
        public virtual int AddStudentToCourse(string coursetitle, string studentemail)
        {
            var coursetitleParameter = coursetitle != null ?
                new ObjectParameter("coursetitle", coursetitle) :
                new ObjectParameter("coursetitle", typeof(string));
    
            var studentemailParameter = studentemail != null ?
                new ObjectParameter("studentemail", studentemail) :
                new ObjectParameter("studentemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddStudentToCourse", coursetitleParameter, studentemailParameter);
        }
    
        public virtual int AddTrainerToCourse(string coursetitle, string traineremail)
        {
            var coursetitleParameter = coursetitle != null ?
                new ObjectParameter("coursetitle", coursetitle) :
                new ObjectParameter("coursetitle", typeof(string));
    
            var traineremailParameter = traineremail != null ?
                new ObjectParameter("traineremail", traineremail) :
                new ObjectParameter("traineremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddTrainerToCourse", coursetitleParameter, traineremailParameter);
        }
    
        public virtual int DeleteAllAssignmentsFromCourse(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAllAssignmentsFromCourse", titleParameter);
        }
    
        public virtual int DeleteAllStudentsFromCourse(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAllStudentsFromCourse", titleParameter);
        }
    
        public virtual int DeleteAllTrainersFromCourse(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAllTrainersFromCourse", titleParameter);
        }
    
        public virtual int DeleteAssignment(string assignmenttitle)
        {
            var assignmenttitleParameter = assignmenttitle != null ?
                new ObjectParameter("assignmenttitle", assignmenttitle) :
                new ObjectParameter("assignmenttitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAssignment", assignmenttitleParameter);
        }
    
        public virtual int DeleteAssignmentFromCourse(string coursetitle, string assignmenttitle)
        {
            var coursetitleParameter = coursetitle != null ?
                new ObjectParameter("coursetitle", coursetitle) :
                new ObjectParameter("coursetitle", typeof(string));
    
            var assignmenttitleParameter = assignmenttitle != null ?
                new ObjectParameter("assignmenttitle", assignmenttitle) :
                new ObjectParameter("assignmenttitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAssignmentFromCourse", coursetitleParameter, assignmenttitleParameter);
        }
    
        public virtual int DeleteCourse(string coursetitle)
        {
            var coursetitleParameter = coursetitle != null ?
                new ObjectParameter("coursetitle", coursetitle) :
                new ObjectParameter("coursetitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCourse", coursetitleParameter);
        }
    
        public virtual int DeleteStudent(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteStudent", emailParameter);
        }
    
        public virtual int DeleteStudentFromAssignment(string studentemail, string assignmenttitle)
        {
            var studentemailParameter = studentemail != null ?
                new ObjectParameter("studentemail", studentemail) :
                new ObjectParameter("studentemail", typeof(string));
    
            var assignmenttitleParameter = assignmenttitle != null ?
                new ObjectParameter("assignmenttitle", assignmenttitle) :
                new ObjectParameter("assignmenttitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteStudentFromAssignment", studentemailParameter, assignmenttitleParameter);
        }
    
        public virtual int DeleteStudentFromCourse(string coursetitle, string studentemail)
        {
            var coursetitleParameter = coursetitle != null ?
                new ObjectParameter("coursetitle", coursetitle) :
                new ObjectParameter("coursetitle", typeof(string));
    
            var studentemailParameter = studentemail != null ?
                new ObjectParameter("studentemail", studentemail) :
                new ObjectParameter("studentemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteStudentFromCourse", coursetitleParameter, studentemailParameter);
        }
    
        public virtual int DeleteTrainer(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTrainer", emailParameter);
        }
    
        public virtual int DeleteTrainerFromCourse(string coursetitle, string traineremail)
        {
            var coursetitleParameter = coursetitle != null ?
                new ObjectParameter("coursetitle", coursetitle) :
                new ObjectParameter("coursetitle", typeof(string));
    
            var traineremailParameter = traineremail != null ?
                new ObjectParameter("traineremail", traineremail) :
                new ObjectParameter("traineremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTrainerFromCourse", coursetitleParameter, traineremailParameter);
        }
    
        public virtual ObjectResult<GetAllAssignments_Result> GetAllAssignments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllAssignments_Result>("GetAllAssignments");
        }
    
        public virtual ObjectResult<GetAllAssignmentsOfCourseById_Result> GetAllAssignmentsOfCourseById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllAssignmentsOfCourseById_Result>("GetAllAssignmentsOfCourseById", idParameter);
        }
    
        public virtual ObjectResult<GetAllAssignmentsOfCourses_Result> GetAllAssignmentsOfCourses(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllAssignmentsOfCourses_Result>("GetAllAssignmentsOfCourses", titleParameter);
        }
    
        public virtual ObjectResult<GetAllAssignmentsOfOneStudent_Result> GetAllAssignmentsOfOneStudent(string coursetitle, string studentemail)
        {
            var coursetitleParameter = coursetitle != null ?
                new ObjectParameter("coursetitle", coursetitle) :
                new ObjectParameter("coursetitle", typeof(string));
    
            var studentemailParameter = studentemail != null ?
                new ObjectParameter("studentemail", studentemail) :
                new ObjectParameter("studentemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllAssignmentsOfOneStudent_Result>("GetAllAssignmentsOfOneStudent", coursetitleParameter, studentemailParameter);
        }
    
        public virtual ObjectResult<GetAllAssignmentsOfStudent_Result> GetAllAssignmentsOfStudent(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllAssignmentsOfStudent_Result>("GetAllAssignmentsOfStudent", emailParameter);
        }
    
        public virtual ObjectResult<GetAllAssignmentsOfStudentById_Result> GetAllAssignmentsOfStudentById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllAssignmentsOfStudentById_Result>("GetAllAssignmentsOfStudentById", idParameter);
        }
    
        public virtual ObjectResult<GetAllAssignmentsPerCourseAndStudent_Result> GetAllAssignmentsPerCourseAndStudent(string coursetitle, string studentemail)
        {
            var coursetitleParameter = coursetitle != null ?
                new ObjectParameter("coursetitle", coursetitle) :
                new ObjectParameter("coursetitle", typeof(string));
    
            var studentemailParameter = studentemail != null ?
                new ObjectParameter("studentemail", studentemail) :
                new ObjectParameter("studentemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllAssignmentsPerCourseAndStudent_Result>("GetAllAssignmentsPerCourseAndStudent", coursetitleParameter, studentemailParameter);
        }
    
        public virtual ObjectResult<GetAllAssignmentsPerCourseAndStudentByIds_Result> GetAllAssignmentsPerCourseAndStudentByIds(Nullable<int> c_id, Nullable<int> s_id)
        {
            var c_idParameter = c_id.HasValue ?
                new ObjectParameter("c_id", c_id) :
                new ObjectParameter("c_id", typeof(int));
    
            var s_idParameter = s_id.HasValue ?
                new ObjectParameter("s_id", s_id) :
                new ObjectParameter("s_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllAssignmentsPerCourseAndStudentByIds_Result>("GetAllAssignmentsPerCourseAndStudentByIds", c_idParameter, s_idParameter);
        }
    
        public virtual ObjectResult<GetAllCourses_Result> GetAllCourses()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCourses_Result>("GetAllCourses");
        }
    
        public virtual ObjectResult<GetAllStudents_Result> GetAllStudents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStudents_Result>("GetAllStudents");
        }
    
        public virtual ObjectResult<GetAllStudentsOfAssignment_Result> GetAllStudentsOfAssignment(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStudentsOfAssignment_Result>("GetAllStudentsOfAssignment", titleParameter);
        }
    
        public virtual ObjectResult<GetAllStudentsOfCourseById_Result> GetAllStudentsOfCourseById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStudentsOfCourseById_Result>("GetAllStudentsOfCourseById", idParameter);
        }
    
        public virtual ObjectResult<GetAllStudentsOfCourses_Result> GetAllStudentsOfCourses(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStudentsOfCourses_Result>("GetAllStudentsOfCourses", titleParameter);
        }
    
        public virtual ObjectResult<GetAllStudentsSubmitsAssOnSameWeek_Result> GetAllStudentsSubmitsAssOnSameWeek()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStudentsSubmitsAssOnSameWeek_Result>("GetAllStudentsSubmitsAssOnSameWeek");
        }
    
        public virtual ObjectResult<GetAllStudentsSubmitsAssOnSameWeekAsDate_Result> GetAllStudentsSubmitsAssOnSameWeekAsDate(string date)
        {
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStudentsSubmitsAssOnSameWeekAsDate_Result>("GetAllStudentsSubmitsAssOnSameWeekAsDate", dateParameter);
        }
    
        public virtual ObjectResult<GetAllStudentsThatBelongMoreToOneCourse_Result> GetAllStudentsThatBelongMoreToOneCourse()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllStudentsThatBelongMoreToOneCourse_Result>("GetAllStudentsThatBelongMoreToOneCourse");
        }
    
        public virtual ObjectResult<GetAllTrainers_Result> GetAllTrainers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllTrainers_Result>("GetAllTrainers");
        }
    
        public virtual ObjectResult<GetAllTrainersOfCourseById_Result> GetAllTrainersOfCourseById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllTrainersOfCourseById_Result>("GetAllTrainersOfCourseById", idParameter);
        }
    
        public virtual ObjectResult<GetAllTrainersOfCourses_Result> GetAllTrainersOfCourses(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllTrainersOfCourses_Result>("GetAllTrainersOfCourses", titleParameter);
        }
    
        public virtual ObjectResult<GetAssignmentById_Result> GetAssignmentById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAssignmentById_Result>("GetAssignmentById", idParameter);
        }
    
        public virtual ObjectResult<GetAssignmentByTitle_Result> GetAssignmentByTitle(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAssignmentByTitle_Result>("GetAssignmentByTitle", titleParameter);
        }
    
        public virtual ObjectResult<GetCourseById_Result> GetCourseById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCourseById_Result>("GetCourseById", idParameter);
        }
    
        public virtual ObjectResult<GetCourseByTitle_Result> GetCourseByTitle(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCourseByTitle_Result>("GetCourseByTitle", titleParameter);
        }
    
        public virtual ObjectResult<string> GetCourseTitleByAssignmentTitle(string title)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetCourseTitleByAssignmentTitle", titleParameter);
        }
    
        public virtual ObjectResult<GetStudentById_Result> GetStudentById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStudentById_Result>("GetStudentById", idParameter);
        }
    
        public virtual ObjectResult<GetTrainerById_Result> GetTrainerById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTrainerById_Result>("GetTrainerById", idParameter);
        }
    
        public virtual int InsertAssignment(string title, string startdate, string enddate, string description)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var startdateParameter = startdate != null ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertAssignment", titleParameter, startdateParameter, enddateParameter, descriptionParameter);
        }
    
        public virtual int InsertCourse(string title, string startdate, string enddate, string description)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var startdateParameter = startdate != null ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCourse", titleParameter, startdateParameter, enddateParameter, descriptionParameter);
        }
    
        public virtual int InsertStudent(string firstname, string lastname, string age, string gender, string startdate, string email, string phone)
        {
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var ageParameter = age != null ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var startdateParameter = startdate != null ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStudent", firstnameParameter, lastnameParameter, ageParameter, genderParameter, startdateParameter, emailParameter, phoneParameter);
        }
    
        public virtual int InsertStudentToAssignment(string studentemail, string assignmenttitle)
        {
            var studentemailParameter = studentemail != null ?
                new ObjectParameter("studentemail", studentemail) :
                new ObjectParameter("studentemail", typeof(string));
    
            var assignmenttitleParameter = assignmenttitle != null ?
                new ObjectParameter("assignmenttitle", assignmenttitle) :
                new ObjectParameter("assignmenttitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStudentToAssignment", studentemailParameter, assignmenttitleParameter);
        }
    
        public virtual int InsertTrainer(string firstname, string lastname, string age, string gender, string startdate, string email, string phone)
        {
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var ageParameter = age != null ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var startdateParameter = startdate != null ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTrainer", firstnameParameter, lastnameParameter, ageParameter, genderParameter, startdateParameter, emailParameter, phoneParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UpdateAssignment(string title, string startdate, string enddate, string description, string searchtitle)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var startdateParameter = startdate != null ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var searchtitleParameter = searchtitle != null ?
                new ObjectParameter("searchtitle", searchtitle) :
                new ObjectParameter("searchtitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAssignment", titleParameter, startdateParameter, enddateParameter, descriptionParameter, searchtitleParameter);
        }
    
        public virtual int UpdateAssignmentsDate(string enddate, string searchtitle)
        {
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var searchtitleParameter = searchtitle != null ?
                new ObjectParameter("searchtitle", searchtitle) :
                new ObjectParameter("searchtitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAssignmentsDate", enddateParameter, searchtitleParameter);
        }
    
        public virtual int UpdateAssignmentsDescription(string description, string searchtitle)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var searchtitleParameter = searchtitle != null ?
                new ObjectParameter("searchtitle", searchtitle) :
                new ObjectParameter("searchtitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAssignmentsDescription", descriptionParameter, searchtitleParameter);
        }
    
        public virtual int UpdateAssignmentsTitle(string title, string searchtitle)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var searchtitleParameter = searchtitle != null ?
                new ObjectParameter("searchtitle", searchtitle) :
                new ObjectParameter("searchtitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAssignmentsTitle", titleParameter, searchtitleParameter);
        }
    
        public virtual int UpdateCourse(string title, string startdate, string enddate, string description, string searchtitle)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var startdateParameter = startdate != null ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(string));
    
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var searchtitleParameter = searchtitle != null ?
                new ObjectParameter("searchtitle", searchtitle) :
                new ObjectParameter("searchtitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCourse", titleParameter, startdateParameter, enddateParameter, descriptionParameter, searchtitleParameter);
        }
    
        public virtual int UpdateCourseEndDate(string enddate, string searchtitle)
        {
            var enddateParameter = enddate != null ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(string));
    
            var searchtitleParameter = searchtitle != null ?
                new ObjectParameter("searchtitle", searchtitle) :
                new ObjectParameter("searchtitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCourseEndDate", enddateParameter, searchtitleParameter);
        }
    
        public virtual int UpdateCourseEndDescription(string description, string searchtitle)
        {
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var searchtitleParameter = searchtitle != null ?
                new ObjectParameter("searchtitle", searchtitle) :
                new ObjectParameter("searchtitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCourseEndDescription", descriptionParameter, searchtitleParameter);
        }
    
        public virtual int UpdateCourseTitle(string title, string searchtitle)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var searchtitleParameter = searchtitle != null ?
                new ObjectParameter("searchtitle", searchtitle) :
                new ObjectParameter("searchtitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCourseTitle", titleParameter, searchtitleParameter);
        }
    
        public virtual int UpdateStudent(string firstname, string lastname, Nullable<int> age, string gender, string email, string phone, string searchemail)
        {
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStudent", firstnameParameter, lastnameParameter, ageParameter, genderParameter, emailParameter, phoneParameter, searchemailParameter);
        }
    
        public virtual int UpdateStudentAge(string age, string searchemail)
        {
            var ageParameter = age != null ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStudentAge", ageParameter, searchemailParameter);
        }
    
        public virtual int UpdateStudentEmail(string email, string searchemail)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStudentEmail", emailParameter, searchemailParameter);
        }
    
        public virtual int UpdateStudentFirstName(string firstname, string searchemail)
        {
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStudentFirstName", firstnameParameter, searchemailParameter);
        }
    
        public virtual int UpdateStudentGender(string gender, string searchemail)
        {
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStudentGender", genderParameter, searchemailParameter);
        }
    
        public virtual int UpdateStudentLastName(string lastname, string searchemail)
        {
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStudentLastName", lastnameParameter, searchemailParameter);
        }
    
        public virtual int UpdateStudentPhone(string phone, string searchemail)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStudentPhone", phoneParameter, searchemailParameter);
        }
    
        public virtual int UpdateTrainer(string firstname, string lastname, Nullable<int> age, string gender, string email, string phone, string searchemail)
        {
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTrainer", firstnameParameter, lastnameParameter, ageParameter, genderParameter, emailParameter, phoneParameter, searchemailParameter);
        }
    
        public virtual int UpdateTrainerAge(string age, string searchemail)
        {
            var ageParameter = age != null ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTrainerAge", ageParameter, searchemailParameter);
        }
    
        public virtual int UpdateTrainerEmail(string email, string searchemail)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTrainerEmail", emailParameter, searchemailParameter);
        }
    
        public virtual int UpdateTrainerFirstName(string firstname, string searchemail)
        {
            var firstnameParameter = firstname != null ?
                new ObjectParameter("firstname", firstname) :
                new ObjectParameter("firstname", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTrainerFirstName", firstnameParameter, searchemailParameter);
        }
    
        public virtual int UpdateTrainerGender(string gender, string searchemail)
        {
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTrainerGender", genderParameter, searchemailParameter);
        }
    
        public virtual int UpdateTrainerLastName(string lastname, string searchemail)
        {
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTrainerLastName", lastnameParameter, searchemailParameter);
        }
    
        public virtual int UpdateTrainerPhone(string phone, string searchemail)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var searchemailParameter = searchemail != null ?
                new ObjectParameter("searchemail", searchemail) :
                new ObjectParameter("searchemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTrainerPhone", phoneParameter, searchemailParameter);
        }
    }
}
